site_name: Battle of Midgard Twitch Bot Documentation
site_url: https://adb-web-designs.github.io/vanderwood-twitch-bot/
repo_url: https://github.com/adb-web-designs/vanderwood-twitch-bot
repo_name: adb-web-designs/vanderwood-twitch-bot
copyright: "Copyright &copy; 2022 VanderwoodTV"
theme:
  name: material
  custom_dir: overrides
  palette:
    scheme: slate
    primary: yellow
  features:
    - navigation.indexes
    - navigation.instant
    - navigation.tabs
    - navigation.tabs.sticky
    - toc.integrate
    - navigation.top
extra:
  social:
    - icon: fontawesome/brands/twitch
      link: https://www.twitch.tv/VANDERWOODTV
  version:
    provider: mike
    default: latest
plugins:
  - search:
      lang: en
  - social:
      cards: true
markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences